### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by sursu** [kitsunyan/intel-undervolt#51]
How to uninstall `intel-undervolt`?

The following does not seem to be doing that:
```
$ sudo make uninstall

make: *** No rule to make target 'uninstall'.  Stop.
```

**Comment by kitsunyan** [comment]
There is no uninstall rule in make file. In fact, the program was designed so it was packaged instead of manual running `make install`. The install route depends on configuration, I'm not sure it's a good idea to add a complex uninstall rule.

It's easy to uninstall it manually, since there it not so many files to delete. You can ask your distro maintainer to package the program for you, or package it yourself. It's always a better approach.
